name: GitHub Pages Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Install .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Install NPM dependencies
      - name: Install NPM dependencies
        working-directory: ./ProcGenFun.Blazor
        run: npm i

      # Compile Tailwind CSS
      - name: Compile Tailwind CSS
        working-directory: ./ProcGenFun.Blazor
        run: npx tailwindcss -i ./Styles/tailwind.css -o ./wwwroot/css/tailwind.css

      # Publish the site
      - name: Publish
        run: dotnet publish ./ProcGenFun.Blazor/ProcGenFun.Blazor.csproj -c:Release -o:publish -p:GHPages=true -p:GHPagesBase=/

      # Deploy the site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: publish/wwwroot
          force_orphan: true
          publish_branch: gh-pages
